---
version: '3.3'

services:
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - PG_PRIMARY_USER=vagrant
      - PG_PRIMARY_PASSWORD=vagrant
      - PG_DATABASE=cloudcomputing
      - PG_USER=vagrant
      - PG_PASSWORD=vagrant
      - PG_ROOT_PASSWORD=vagrant
      - PG_PRIMARY_PORT=5432
    volumes:
      - pg-primary-vol:/pgdata
    ports:
      - '5432'
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
  replica:
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=replica
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=vagrant
      - PG_PRIMARY_PASSWORD=vagrant
      - PG_DATABASE=cloudcomputing
      - PG_USER=testuser
      - PG_PASSWORD=vagrant
      - PG_ROOT_PASSWORD=vagrant
    volumes:
      - pg-replica-vol:/pgdata
    ports:
      - '5432'
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker

volumes:
  pg-primary-vol:
  pg-replica-vol: